"""Add file_size to Photo and Event models

Revision ID: 142bb28289ef
Revises: 6a3d9d8f9469
Create Date: 2025-11-16 13:12:22.320333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '142bb28289ef'
down_revision: Union[str, Sequence[str], None] = '6a3d9d8f9469'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('cover_image_file_size', sa.String(), nullable=True))
    op.add_column('photos', sa.Column('file_size', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photos', 'file_size')
    op.drop_column('events', 'cover_image_file_size')
    # ### end Alembic commands ###
