"""Add cover_thumbnail_url to Event model

Revision ID: 3752d0fca89d
Revises: 77f87aba05b1
Create Date: 2025-11-16 13:04:29.558832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3752d0fca89d'
down_revision: Union[str, Sequence[str], None] = '77f87aba05b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('cover_thumbnail_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'cover_thumbnail_url')
    # ### end Alembic commands ###
