"""Add public_uploader_identifier to Photo model

Revision ID: 63eb672adbb7
Revises: 983d2d1f30af
Create Date: 2025-11-16 13:29:57.734975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63eb672adbb7'
down_revision: Union[str, Sequence[str], None] = '983d2d1f30af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('public_uploader_identifier', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photos', 'public_uploader_identifier')
    # ### end Alembic commands ###
