"""Add avatar URLs to User model

Revision ID: 6a3d9d8f9469
Revises: 3752d0fca89d
Create Date: 2025-11-16 13:10:20.714247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a3d9d8f9469'
down_revision: Union[str, Sequence[str], None] = '3752d0fca89d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('avatar_thumbnail_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_thumbnail_url')
    op.drop_column('users', 'avatar_url')
    # ### end Alembic commands ###
