"""Initial migration with users, events, and photos tables

Revision ID: 77f87aba05b1
Revises: a558e14adfe5
Create Date: 2025-11-15 06:58:24.033677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77f87aba05b1'
down_revision: Union[str, Sequence[str], None] = 'a558e14adfe5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
