"""Add avatar_file_size to User model

Revision ID: 983d2d1f30af
Revises: 142bb28289ef
Create Date: 2025-11-16 13:12:56.011861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '983d2d1f30af'
down_revision: Union[str, Sequence[str], None] = '142bb28289ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_file_size', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_file_size')
    # ### end Alembic commands ###
